project:
  type: book
  post-render: 
    # - quarto render slides/
    - quarto render thesis/
    # - quarto render manuscript/
    
execute:
  freeze: auto
  echo: true
      
format:
  html:
    theme: 
      - default
      - .custom.scss
    toc-depth: 2
    notebook-links: true
    number-sections: false  
    reference-location: margin
    mermaid:
      theme: neutral

comments:
  hypothesis: true

lightbox: true

book:
  repo-url: "https://github.com/munch-group/hic-compartment-borders"
  repo-actions: [edit, issue, source]  
  title: "Probabilistic Models for Hi-C Compartment Borders"
  author: "Søren Jørgensen"  
  sidebar:
    collapse-level: 1
    search: true  
  chapters:
    - index.qmd
    # - part: "Manuscript"
    #   chapters:
    #   - manuscript/index.qmd 
    - part: "Thesis"
      chapters:
      - thesis/index.qmd 
    # - part: "Slides"
    #   chapters:
    #   - slides/index.qmd 
    - part: "Notebooks"
      chapters: 
      - notebooks/01_prep_e1_values.ipynb
      - notebooks/02_PyMC_independent_bins.ipynb
      - notebooks/03_PyMC_GRW_logit.ipynb
      - notebooks/04_PyMC_GRW_compare.ipynb
      - notebooks/05_PyMC_bernoulli_z.ipynb
    - part: "Workflows"
      chapters: 
      - master_workflow.py
      - workflow.py
    - part: "Reports"
      chapters: 
      - reports/example.qmd
    # - part: "Tables"
    #   chapters: 
    #   - tables/example.ipynb
  downloads: [pdf]
     
bibliography: references.bib

